spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: "root"
    password: ""
    url: jdbc:mysql://localhost/security
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      data-locations:
        - classpath:script.sql
      mode: always
  security:
    user:
      name: user
      password: 1234